# Generated by Django 5.1.1 on 2024-10-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique_for_date='publish'),
        ),
    ]
