# Generated by Django 5.1.1 on 2024-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='films/default.jpg', upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
