# Generated by Django 5.1.1 on 2024-10-09 15:53

import film.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_image_alter_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='films/default.jpg', upload_to=film.models.user_directory_path),
        ),
    ]
