# Generated by Django 5.1.1 on 2024-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_review_rating_review_title_alter_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
