# Generated by Django 5.1.1 on 2024-10-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='calificacion',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
