# Generated by Django 5.1.1 on 2024-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_remove_film_category_film_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, to='film.director'),
        ),
    ]
