# Generated by Django 5.1.1 on 2024-10-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_remove_film_director_film_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
