# Generated by Django 5.1.1 on 2024-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_director_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
