# Generated by Django 5.1.1 on 2024-10-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_director_city_of_birth_director_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='age',
        ),
    ]
